import {Dumbbell,Car,Compass,Users,Leaf,ArrowDown,ShieldCheck} from 'lucide-react';
import {motion,useReducedMotion} from 'motion/react';
import {Button,Heading} from '../components/Shared';
import {asset} from '../data/site';
import {premium} from '../data/premium';
const icons=[Dumbbell,Car,Compass,Users,Leaf];
export default function PremiumExperience(){const reduced=useReducedMotion();return <div className="executive-page">
 <section className="executive-hero"><motion.div initial={reduced?false:{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{duration:.5}}><span className="eyebrow">HEALING TOUCH DPC PREMIUM</span><h1>Healthcare<br/>Without<br/><em>Compromise.</em></h1><p className="executive-lead">An extraordinary level of personalized care, access, convenience, and wellness—designed around you.</p><p>Healing Touch DPC Premium reimagines the traditional healthcare experience through highly personalized physician relationships, enhanced wellness privileges, family benefits, and exceptional convenience.</p><div className="actions"><a className="button" href="#premium-pillars" onClick={e=>{e.preventDefault();document.getElementById('premium-pillars')?.scrollIntoView({behavior:reduced?'instant':'smooth'});}}>Discover the Premium Experience <ArrowDown size={17}/></a><Button to="/contact?interest=Premium" secondary>Request Membership Information</Button></div></motion.div><figure className="executive-visual"><img src={asset('hero/healing-touch-hero.png')} width="1536" height="1024" alt="Warm Healing Touch branded reception interior" fetchPriority="high"/><figcaption><span>THE PRIVILEGE OF PERSONAL CARE</span><p>Considered in every detail.<br/><em>Centered on you.</em></p></figcaption><span className="visual-index">HEALING TOUCH / PREMIUM</span></figure></section>
 <section className="executive-pricing"><div className="membership-insignia" aria-hidden="true">HT<span>PREMIUM</span></div><div className="pricing-intro"><span className="eyebrow">PREMIUM MEMBERSHIP</span><h2>A life well lived.<br/>A membership<br/><em>like no other.</em></h2><p>A highly personalized healthcare and wellness experience designed around your life.</p></div><div className="pricing-amount"><span className="starting">Starting at</span><div>{premium.price}</div><span className="annual">{premium.billing}</span><span className="consultation-label">MEMBERSHIP BY CONSULTATION</span><Button to="/contact?interest=Premium" secondary>Request a Private Consultation</Button></div></section>
 <section className="section premium-pillars" id="premium-pillars"><Heading eyebrow="BEYOND PRIMARY CARE" title="More Than Healthcare. A Complete Wellness Experience.">Premium membership extends the Healing Touch experience beyond the clinic—bringing together personalized care, wellness, convenience, family support, and coordinated healthcare access.</Heading><div className="pillar-experiences">{premium.pillars.map((p,i)=>{const Icon=icons[i];return <article className={`pillar-experience pillar-${i+1}`} key={p.title}><div className="pillar-visual"><span className="pillar-index">0{i+1}</span><Icon strokeWidth={.8} size={110}/><p>{p.short}</p><span className="pillar-signature">THE HEALING TOUCH EXPERIENCE</span></div><div className="pillar-copy"><span className="eyebrow">PREMIUM PRIVILEGE / 0{i+1}</span><h3>{p.title}</h3><p>{p.description}</p><ul>{p.benefits.map(b=><li key={b}><ShieldCheck size={16} strokeWidth={1.2}/>{b}</li>)}</ul></div></article>})}</div></section>
 <section className="section supporting-privileges"><Heading eyebrow="THOUGHTFUL IN EVERY DETAIL" title="Premium Means More."/><div className="privileges-grid">{premium.privileges.map(([title,copy])=><article key={title}><span className="privilege-mark" aria-hidden="true">✧</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section className="section premium-journey"><Heading eyebrow="A RELATIONSHIP, NOT A TRANSACTION" title="Your Premium Journey"/><ol>{premium.journey.map(([title,copy],i)=><li key={title}><span className="journey-step">0{i+1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></section>
 <section className="personal-statement"><div><span className="eyebrow">INTENTIONALLY PERSONAL</span><h2>Exceptional Care<br/>Requires <em>Time.</em></h2></div><div><p>To preserve the highly personalized nature of the Premium experience, membership is designed around a limited patient relationship model.</p><Button to="/contact?interest=Premium" secondary>Request Membership Information</Button></div></section>
 <section className="section executive-closing"><span className="eyebrow">HEALING TOUCH DPC PREMIUM</span><h2>Your Health Deserves<br/>an Exceptional Experience.</h2><p>Discover a healthcare relationship designed around time, access, convenience, wellness, and the people who matter most.</p><div className="actions"><Button to="/contact?interest=Premium">Request a Private Consultation</Button><Button to="/about" secondary>Meet Dr. T</Button></div><p className="concept-disclaimer">{premium.disclaimer}</p><p className="fineprint">Membership is not health insurance.</p></section>
 </div>}
