import {useState} from 'react';
import {useForm} from 'react-hook-form';
import {z} from 'zod';
import {zodResolver} from '@hookform/resolvers/zod';
import {useSearchParams} from 'react-router-dom';
import {submitInquiry} from '../lib/formService';
const schema=z.object({firstName:z.string().trim().min(1,'Enter your first name').max(60),lastName:z.string().trim().min(1,'Enter your last name').max(60),email:z.email('Enter a valid email address'),phone:z.string().max(30),interest:z.enum(['Membership','Premium','Employer','Wellness','General']),preferredContact:z.enum(['Email','Phone']),message:z.string().max(500,'Keep your message under 500 characters'),consent:z.boolean().refine(Boolean,'Please acknowledge the demo form notice')});
type Fields=z.infer<typeof schema>;
export default function InquiryForm(){const [params]=useSearchParams();const interest=params.get('interest');const [status,setStatus]=useState('');const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Fields>({resolver:zodResolver(schema),defaultValues:{interest:['Membership','Premium','Employer','Wellness'].includes(interest||'')?interest as Fields['interest']:'General',preferredContact:'Email'}});
const submit=async(data:Fields)=>{try{setStatus((await submitInquiry(data)).message);}catch{setStatus('We could not complete this request. Please contact the practice directly.');}};
return <form className="inquiry" onSubmit={handleSubmit(submit)} noValidate><span className="eyebrow">LET’S START A CONVERSATION</span><h2>Tell us what interests you.</h2><p className="notice">Local demo · This form does not send or save information. Please do not submit sensitive medical information through this form.</p><div className="form-grid">{(['firstName','lastName','email','phone'] as const).map(name=><label key={name} htmlFor={name}>{({firstName:'First name',lastName:'Last name',email:'Email',phone:'Phone (optional)'})[name]}<input id={name} type={name==='email'?'email':name==='phone'?'tel':'text'} autoComplete={name==='firstName'?'given-name':name==='lastName'?'family-name':name} {...register(name)} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`${name}-error`:undefined}/>{errors[name]&&<span id={`${name}-error`} className="error">{errors[name]?.message}</span>}</label>)}<label htmlFor="interest">I’m interested in<select id="interest" {...register('interest')}>{['Membership','Premium','Employer','Wellness','General'].map(v=><option key={v}>{v}</option>)}</select></label><label htmlFor="preferredContact">Preferred contact method<select id="preferredContact" {...register('preferredContact')}><option>Email</option><option>Phone</option></select></label></div><label htmlFor="message">General message (optional)<textarea id="message" rows={4} maxLength={500} {...register('message')}/>{errors.message&&<span className="error">{errors.message.message}</span>}</label><label className="checkbox"><input type="checkbox" {...register('consent')} aria-invalid={!!errors.consent}/>I understand this is a demo and will not include medical information.</label>{errors.consent&&<p className="error" role="alert">{errors.consent.message}</p>}<button className="button" disabled={isSubmitting}>{isSubmitting?'Validating…':'Validate demo inquiry'}</button><p role="status" className="form-status">{status}</p></form>}
