import {ArrowUpRight,HeartHandshake,Clock,MessageCircle,Leaf,CalendarDays,ShieldCheck,MapPin,Phone,Mail} from 'lucide-react';
import {Link} from 'react-router-dom';
import {asset,siteConfig as site} from '../data/site';
import {benefits} from '../data/services';
import {memberships} from '../data/memberships';
import {faqs} from '../data/faq';
const icons=[HeartHandshake,Clock,MessageCircle,Leaf,CalendarDays,ShieldCheck];
export function Button({to,children,secondary=false}:{to:string;children:React.ReactNode;secondary?:boolean}){return <Link className={`button ${secondary?'secondary':''}`} to={to}>{children}<ArrowUpRight size={17}/></Link>}
export function Heading({eyebrow,title,children}:{eyebrow:string;title:string;children?:React.ReactNode}){return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children&&<p>{children}</p>}</div>}
export function Benefits(){return <div className="benefit-grid">{benefits.map(([title,description],i)=>{const Icon=icons[i];return <article className="benefit" key={title}><Icon size={27} strokeWidth={1.4}/><h3>{title}</h3><p>{description}</p><span className="card-number">0{i+1}</span></article>})}</div>}
export function MembershipCards(){return <div className="membership-grid">{memberships.map(m=><article className={`membership ${m.featured?'featured':''}`} key={m.id}><span className="eyebrow">{m.featured?'THE PREMIUM CONCEPT':'THE FOUNDATION OF YOUR CARE'}</span><h3>{m.name}</h3><p>{m.description}</p><div className="price">{m.price}<small>{m.billingFrequency}</small></div><ul>{m.benefits.map(b=><li key={b}><ShieldCheck size={16}/>{b}</li>)}</ul><Button to={`/contact?interest=${m.featured?'Premium':'Membership'}`} secondary={m.featured}>{m.cta}</Button><p className="fineprint">{m.disclaimer}</p></article>)}</div>}
export function Physician({full=false}:{full?:boolean}){return <div className="editorial"><figure className="physician-image"><img src={asset('physician/dr-t.jpg')} width="960" height="1280" alt="Dr. Teresa Ayela-Uwangue" loading="lazy" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src=asset('physician/dr-t-placeholder.svg')}}/><figcaption>DR. TERESA AYELA-UWANGUE · YOUR PARTNER IN HEALTH</figcaption></figure><div><span className="eyebrow">A FAMILIAR FACE. A TRUSTED PARTNER.</span><h2>Meet Dr. T.</h2><p className="lead">Care begins with knowing the person behind the patient.</p><p>Dr. Teresa Ayela-Uwangue is double board-certified in Internal Medicine and Pediatrics. Her approach centers on listening, education, prevention, and the whole person.</p>{full&&<><p>She earned her Bachelor of Science in Biological Science at Rochester Institute of Technology and her medical degree at the University at Buffalo. She completed Internal Medicine and Pediatrics residency training at Penn State’s Hershey Medical Center, where she served as chief resident.</p><p>Her practice is built around a lasting physician-patient relationship, with time to understand your story and explain your care.</p></>}<Button to={full?'/contact':'/about'}>{full?'Start a conversation':'Get to know Dr. T'}</Button></div></div>}
export function FAQList(){return <div className="faq-list">{faqs.map(([category,q,a])=><details key={q}><summary><span><small>{category}</small>{q}</span><span className="plus" aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div>}
export function OffersEmpty(){return <div className="empty-state"><span className="empty-symbol">✧</span><span className="eyebrow">SOMETHING THOUGHTFUL IS ON THE HORIZON</span><h2>New Premium Opportunities<br/>Are Coming Soon</h2><p>We’re reserving this space for verified offers and member privileges. Ask the practice about current opportunities.</p><Button to="/contact">Ask about current offers</Button></div>}
export function ContactDetails(){return <div className="contact-details"><span className="eyebrow">ROOTED IN GILBERT, ARIZONA</span><h2>A personal connection.<br/>Close to home.</h2><p><MapPin size={20}/>{site.address}</p><p><Phone size={20}/><a href={site.phoneHref}>{site.phone}</a></p><p><Mail size={20}/><a href={`mailto:${site.email}`}>{site.email}</a></p><p>{site.hours}</p><a className="text-link" href={site.mapsUrl} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={17}/><span className="sr-only">(opens in a new tab)</span></a></div>}
export function PremiumCTA(){return <section className="purple-cta"><span className="eyebrow">EXCEPTIONAL HEALTHCARE. PERSONALLY DELIVERED.</span><h2>Your Healthcare Experience<br/>Can Be Different.</h2><p>Discover a more personal approach to healthcare through Healing Touch DPC Premium.</p><div className="actions"><Button to="/memberships" secondary>Explore Membership</Button><Link className="text-link light" to="/contact">Contact Healing Touch <ArrowUpRight size={18}/></Link></div></section>}
