import {Component,lazy,Suspense,useEffect,useRef,useState} from 'react';
import type {ReactNode} from 'react';
import {Link,NavLink,Route,Routes,useLocation} from 'react-router-dom';
import {ArrowUpRight,Menu,X,Sparkles} from 'lucide-react';
import {asset,navigation,siteConfig as site} from './data/site';
import {isPromotionActive} from './lib/promotions';
const Home=lazy(()=>import('./pages/Home'));
const ContentPage=lazy(()=>import('./pages/ContentPage'));
function Logo(){return <Link to="/" className="brand" aria-label="Healing Touch DPC Premium home"><img src={asset('brand/logo-placeholder.svg')} width="50" height="50" alt=""/><span>Healing Touch<small>DIRECT PRIMARY CARE</small><span className="brand-premium">P R E M I U M</span></span></Link>}
function Navigation(){const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);const drawer=useRef<HTMLDialogElement>(null);const location=useLocation();useEffect(()=>{setOpen(false);},[location]);useEffect(()=>{const dialog=drawer.current;if(open){dialog?.showModal();document.body.style.overflow='hidden';}else{dialog?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[open]);return <><div className="utility"><span>PERSONAL PRIMARY CARE · GILBERT, AZ</span><a href={site.mainWebsite}>Main Healing Touch Site <ArrowUpRight size={12}/></a></div><header><div className="header-top"><Logo/><div className="header-actions"><a href={site.phoneHref} className="header-phone">{site.phone}</a><Link className="button small" to={site.membershipCTA.url}>{site.membershipCTA.label}<ArrowUpRight size={15}/></Link><button ref={toggle} className="menu-toggle" aria-label="Open navigation" aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><Menu/></button></div></div><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(([name,to])=><NavLink key={to} end to={to}>{name}</NavLink>)}</nav></header><dialog ref={drawer} className="mobile-drawer" aria-label="Navigation menu" onCancel={()=>setOpen(false)} onClose={()=>{setOpen(false);toggle.current?.focus();}} onClick={e=>{if(e.target===drawer.current)setOpen(false)}}><div className="drawer-inner"><div className="drawer-heading"><Logo/><button className="icon-button" aria-label="Close navigation" onClick={()=>setOpen(false)}><X/></button></div><span className="eyebrow">YOUR HEALING TOUCH EXPERIENCE</span><nav aria-label="Mobile navigation">{navigation.map(([name,to],i)=><NavLink end to={to} key={to} onClick={()=>setOpen(false)}><small>{String(i+1).padStart(2,'0')}</small>{name}<ArrowUpRight size={18}/></NavLink>)}</nav><a href={site.mainWebsite} className="text-link">Return to the main practice site ↗</a><a href={site.phoneHref}>{site.phone}</a></div></dialog></>}
function Footer(){return <footer><div className="footer-grid"><div><Logo/><p>Exceptional healthcare.<br/>Personally delivered.</p><a className="text-link light" href={site.mainWebsite}>Return to Healing Touch DPC <ArrowUpRight size={16}/></a></div><div><span className="eyebrow">EXPLORE</span>{navigation.slice(1,6).map(([name,to])=><Link to={to} key={to}>{name}</Link>)}</div><div><span className="eyebrow">CONNECT</span><a href={site.phoneHref}>{site.phone}</a><a href={`mailto:${site.email}`}>{site.email}</a><p>{site.address}</p><p>{site.hours}</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Healing Touch DPC Premium</span><div><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms</Link><Link to="/accessibility">Accessibility</Link></div><span>Membership is not health insurance.</span></div></footer>}
function PageEffects(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});const names:Record<string,string>={'/':'Home','/premium':'Premium Experience','/about':'About Dr. T','/memberships':'Memberships','/offers':'Exclusive Offers','/wellness':'Wellness','/employers':'Employers','/testimonials':'Testimonials','/faq':'FAQ','/contact':'Contact','/privacy':'Privacy Policy','/terms':'Terms','/accessibility':'Accessibility'};document.title=`${names[pathname]||'Page not found'} | ${site.premiumName}`;document.querySelector('meta[name="description"]')?.setAttribute('content',`${names[pathname]||'Explore'} with Healing Touch Direct Primary Care in Gilbert, Arizona. Relationship-centered healthcare, personally delivered.`);if(site.canonicalOrigin){let canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical);}canonical.href=site.canonicalOrigin;}document.getElementById('main-content')?.focus({preventScroll:true});},[pathname]);return null;}
class ErrorBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<section className="section"><h1>A moment of pause.</h1><p>We couldn’t display this page. Please reload or contact the practice.</p><a className="button" href={import.meta.env.BASE_URL}>Reload the website</a></section>:this.props.children;}}
function Concierge(){const [open,setOpen]=useState(false);return site.conciergeEnabled?<div className="concierge"><button className="button" onClick={()=>setOpen(!open)} aria-expanded={open}><Sparkles size={18}/>Premium Concierge</button>{open&&<div className="concierge-panel"><h3>Premium Concierge Coming Soon</h3><p>Future support for public practice information and navigation. No medical advice or patient data collection.</p></div>}</div>:null;}
export default function App(){return <><a href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus();}} className="skip-link">Skip to content</a>{site.announcement.enabled&&isPromotionActive(site.announcement)&&<div className="announcement">{site.announcement.message}<Link to={site.announcement.ctaUrl}>{site.announcement.ctaLabel} <ArrowUpRight size={13}/></Link></div>}<Navigation/><PageEffects/><main id="main-content" tabIndex={-1}><ErrorBoundary><Suspense fallback={<div className="section" role="status">Preparing your experience…</div>}><Routes><Route path="/" element={<Home/>}/><Route path="*" element={<ContentPage/>}/></Routes></Suspense></ErrorBoundary></main><Footer/><Concierge/></>}

